/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposyaza;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FrmBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmBarang
     */
    //Perintah memanggil class DATABASE
    //Instasiasi objek ( Class)
    Database db = new Database();
    
    public FrmBarang() {
        initComponents();
        
        //Mengatur form ditengah-tengah layar
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setLocation(x, y);
        
        //Menghubungkan ke database
        db.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jkd_brg = new javax.swing.JTextField();
        jnama_brg = new javax.swing.JTextField();
        jjml = new javax.swing.JTextField();
        jharga = new javax.swing.JTextField();
        jbtHapus = new javax.swing.JButton();
        jbtBatal = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jbtSimpan = new javax.swing.JButton();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel1.setText("Kode Barang :");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setText("Nama Barang :");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel3.setText("Harga Barang :");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel4.setText("Jumlah :");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jkd_brg.setMargin(new java.awt.Insets(4, 3, 4, 3));
        jkd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_brgActionPerformed(evt);
            }
        });

        jnama_brg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jnama_brg.setMargin(new java.awt.Insets(4, 3, 4, 3));
        jnama_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnama_brgActionPerformed(evt);
            }
        });

        jjml.setMargin(new java.awt.Insets(4, 3, 4, 3));
        jjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjmlActionPerformed(evt);
            }
        });

        jharga.setMargin(new java.awt.Insets(4, 3, 4, 3));
        jharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhargaActionPerformed(evt);
            }
        });

        jbtHapus.setBackground(new java.awt.Color(204, 204, 204));
        jbtHapus.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtHapus.setText("Hapus");
        jbtHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtHapus.setMargin(new java.awt.Insets(5, 15, 5, 15));
        jbtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHapusActionPerformed(evt);
            }
        });

        jbtBatal.setBackground(new java.awt.Color(204, 204, 204));
        jbtBatal.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtBatal.setText("Batal");
        jbtBatal.setMargin(new java.awt.Insets(5, 15, 5, 15));
        jbtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBatalActionPerformed(evt);
            }
        });

        jbtKeluar.setBackground(new java.awt.Color(255, 102, 102));
        jbtKeluar.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtKeluar.setText("Keluar");
        jbtKeluar.setMargin(new java.awt.Insets(5, 15, 5, 15));
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        jbtEdit.setBackground(new java.awt.Color(204, 204, 204));
        jbtEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtEdit.setText("Edit");
        jbtEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtEdit.setMargin(new java.awt.Insets(5, 15, 5, 15));
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtSimpan.setBackground(new java.awt.Color(204, 204, 204));
        jbtSimpan.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtSimpan.setText("Simpan");
        jbtSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtSimpan.setMargin(new java.awt.Insets(5, 15, 5, 15));
        jbtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSimpanActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(102, 204, 255));
        label2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        label2.setText("Input Data Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jbtKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnama_brg)
                            .addComponent(jharga)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjml, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbtBatal)
                    .addComponent(jbtKeluar)
                    .addComponent(jbtEdit)
                    .addComponent(jbtSimpan)
                    .addComponent(jbtHapus))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_brgActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambilData("select * from tbarang where kd_brg='" + jkd_brg.getText() + "'");
            if (rs.next()) {
                jnama_brg.setText(rs.getString("nama_brg"));
                jjml.setText(rs.getString("jml"));
                jharga.setText(rs.getString("harga"));
            } else {
                JOptionPane.showMessageDialog(null, "Data belum terdaftar, tambahkan");
                jnama_brg.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jkd_brgActionPerformed

    private void jbtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambilData("select * from tbarang where kd_brg='" + jkd_brg.getText() + "'");
            if (rs.next()) {
                int n = JOptionPane.showConfirmDialog(this, "Anda yakin?", "RPL message",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from tbarang where kd_brg='"+jkd_brg.getText()+"'");
                    JOptionPane.showMessageDialog(null, "Data sudah terhapus");
                }
                } else {
                JOptionPane.showMessageDialog(null, "Data tidak terdaftar");
            }
            jkd_brg.setText("");
            jnama_brg.setText("");
            jjml.setText("");
            jharga.setText("");
            jkd_brg.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtHapusActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Yakin keluar dari aplikasi ini?",
                "Reminder RPL", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose(); 
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    private void jbtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBatalActionPerformed
        // TODO add your handling code here:
        jkd_brg.setText("");
        jnama_brg.setText("");
        jjml.setText("");
        jharga.setText("");
    }//GEN-LAST:event_jbtBatalActionPerformed

    private void jbtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSimpanActionPerformed
        // TODO add your handling code here:
        
        try {
            
            ResultSet rs=db.ambilData("select * from tbarang where kd_brg='"+jkd_brg.getText()+"'");
            if (rs.next()) {
                
                JOptionPane.showMessageDialog(null, "Data telah terdaftar");
                jnama_brg.setText(rs.getString("nama_brg"));
                jjml.setText(rs.getString("jml"));
                jharga.setText(rs.getString("harga"));
            } else {
                
                db.aksi("insert into tbarang(kd_brg,nama_brg,jml,harga)values('"+jkd_brg.getText()+"',"
                        + "'"+jnama_brg.getText()+"',"
                        + "'"+jjml.getText()+"',"
                        + "'"+jharga.getText()+"')");
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                jkd_brg.setText("");
                jnama_brg.setText("");
                jjml.setText("");
                jharga.setText("");
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtSimpanActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambilData("select * from tbarang where kd_brg='"+jkd_brg.getText()+"'");
            if (rs.next()) {
                db.aksi("update tbarang set nama_brg='"+jnama_brg.getText()+"',jml='"+jjml.getText()+"',harga='"+jharga.getText()+"'"
                    + "where kd_brg='"+ jkd_brg.getText()+"'");
                JOptionPane.showMessageDialog(null, "Data berhasil di edit");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang hendak di edit....");
            }
            jkd_brg.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jnama_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnama_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnama_brgActionPerformed

    private void jjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjmlActionPerformed

    private void jhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtBatal;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtHapus;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtSimpan;
    private javax.swing.JTextField jharga;
    private javax.swing.JTextField jjml;
    private javax.swing.JTextField jkd_brg;
    private javax.swing.JTextField jnama_brg;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
