/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposyaza;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class FrmKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmKaryawan
     */
    Database db = new Database();
    public FrmKaryawan() {
        initComponents();
        //Mengatur form ditengah-tengah layar
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        this.setLocation(x, y);
        
        //Menghubungkan ke database
        db.koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jkd_kry = new javax.swing.JTextField();
        jnama_kry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jalamat = new javax.swing.JTextArea();
        jtelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jusername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtSimpan = new javax.swing.JButton();
        jbtEdit = new javax.swing.JButton();
        jbtHapus = new javax.swing.JButton();
        jbtBatal = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();
        jjklm = new javax.swing.JComboBox<>();
        jpassword = new javax.swing.JPasswordField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(102, 204, 255));
        label1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        label1.setText("Input Data Karyawan");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel1.setText("Kode Karyawan :");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setText("Nama :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel3.setText("Jenis Kelamin :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel4.setText("Alamat :");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel5.setText("Telepon :");

        jkd_kry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_kryActionPerformed(evt);
            }
        });

        jalamat.setColumns(20);
        jalamat.setRows(5);
        jScrollPane1.setViewportView(jalamat);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel8.setText("Username :");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel9.setText("Password :");

        jbtSimpan.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtSimpan.setText("Simpan");
        jbtSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSimpanActionPerformed(evt);
            }
        });

        jbtEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtEdit.setText("Edit");
        jbtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditActionPerformed(evt);
            }
        });

        jbtHapus.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtHapus.setText("Hapus");
        jbtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHapusActionPerformed(evt);
            }
        });

        jbtBatal.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtBatal.setText("Batal");
        jbtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBatalActionPerformed(evt);
            }
        });

        jbtKeluar.setBackground(new java.awt.Color(255, 102, 102));
        jbtKeluar.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jbtKeluar.setText("Keluar");
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        jjklm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jkd_kry)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtelepon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                    .addComponent(jusername)
                                    .addComponent(jnama_kry)
                                    .addComponent(jjklm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpassword))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jbtSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtKeluar)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jkd_kry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jnama_kry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jjklm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSimpan)
                    .addComponent(jbtEdit)
                    .addComponent(jbtHapus)
                    .addComponent(jbtBatal)
                    .addComponent(jbtKeluar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkd_kryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_kryActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambilData("select * from tkaryawan where kd_kry='" + jkd_kry.getText() + "'");
            if (rs.next()) {
                jnama_kry.setText(rs.getString("nama"));
                jjklm.setSelectedItem(rs.getString("jklm"));
                jalamat.setText(rs.getString("alamat"));
                jtelepon.setText(rs.getString("telepon"));
                jusername.setText(rs.getString("username"));
                jpassword.setText(rs.getString("password"));
            } else {
                JOptionPane.showMessageDialog(null, "Data belum terdaftar, tambahkan");
                jnama_kry.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jkd_kryActionPerformed

    private void jbtSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSimpanActionPerformed
        // TODO add your handling code here:
        
        try {
            ResultSet rs=db.ambilData("select * from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
            if (rs.next()) {
                
                JOptionPane.showMessageDialog(null, "Data telah terdaftar");
                jnama_kry.setText(rs.getString("nama"));
                jjklm.setSelectedItem(rs.getString("jklm"));
                jalamat.setText(rs.getString("alamat"));
                jtelepon.setText(rs.getString("telepon"));
                jusername.setText(rs.getString("username"));
                jpassword.setText(rs.getString("password"));
            } else {
                
                db.aksi("insert into tkaryawan(kd_kry,nama,jklm,alamat,telepon,username,password)values('"+jkd_kry.getText()+"',"
                        + "'"+jnama_kry.getText()+"',"
                        + "'"+jjklm.getSelectedItem()+"',"
                        + "'"+jalamat.getText()+"',"
                        + "'"+jtelepon.getText()+"',"
                        + "'"+jusername.getText()+"',"
                        + "'"+jpassword.getText()+"')");
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                jkd_kry.setText("");
                jnama_kry.setText("");
                jjklm.setSelectedItem("");
                jalamat.setText("");
                jtelepon.setText("");
                jusername.setText("");
                jpassword.setText("");
            }
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtSimpanActionPerformed

    private void jbtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambilData("select * from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
            if (rs.next()) {
                db.aksi("update tkaryawan set nama='"+jnama_kry.getText()+"',jklm='"+jjklm.getSelectedItem()+"',alamat='"+jalamat.getText()+"',telepon='"+jtelepon.getText()+"',username='"+jusername.getText()+"',password='"+jpassword.getText()+"'"
                + "where kd_kry='"+ jkd_kry.getText()+"'");
                JOptionPane.showMessageDialog(null, "Data berhasil di edit");
            } else {
                JOptionPane.showMessageDialog(null, "Tidak ada data yang hendak di edit....");
            }
            jkd_kry.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jbtEditActionPerformed

    private void jbtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHapusActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs=db.ambilData("select * from tkaryawan where kd_kry='" + jkd_kry.getText() + "'");
            if (rs.next()) {
                int n = JOptionPane.showConfirmDialog(this, "Anda yakin?", "RPL message",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
                if (n == JOptionPane.YES_OPTION) {
                    db.aksi("delete from tkaryawan where kd_kry='"+jkd_kry.getText()+"'");
                    JOptionPane.showMessageDialog(null, "Data sudah terhapus");
                }
                } else {
                JOptionPane.showMessageDialog(null, "Data tidak terdaftar");
            }
            jkd_kry.setText("");
            jnama_kry.setText("");
            jjklm.setSelectedItem("");
            jalamat.setText("");
            jtelepon.setText("");
            jusername.setText("");
            jpassword.setText("");
            jkd_kry.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtHapusActionPerformed

    private void jbtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBatalActionPerformed
        // TODO add your handling code here:
        jkd_kry.setText("");
        jnama_kry.setText("");
        jjklm.setSelectedItem("");
        jalamat.setText("");
        jtelepon.setText("");
        jusername.setText("");
        jpassword.setText("");
    }//GEN-LAST:event_jbtBatalActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Yakin keluar dari aplikasi ini?",
                "Reminder RPL", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose(); 
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jalamat;
    private javax.swing.JButton jbtBatal;
    private javax.swing.JButton jbtEdit;
    private javax.swing.JButton jbtHapus;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtSimpan;
    private javax.swing.JComboBox<String> jjklm;
    private javax.swing.JTextField jkd_kry;
    private javax.swing.JTextField jnama_kry;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtelepon;
    private javax.swing.JTextField jusername;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
