/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prjposyaza;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FrmTransBarang extends javax.swing.JInternalFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    long sumTotal = 0;
    
    Database db = new Database();

    /**
     * Creates new form FrmTransBarang
     */
    public FrmTransBarang() {
        db.koneksi();
        initComponents();
        
        //Mengatur form rata tengah
        Dimension Posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (Posisi.width - this.getWidth()) / 2;
        int y = (Posisi.height - this.getHeight()) / 2;
        this.setLocation(x, y);
        
        //Menampilkan tanggal otomatis
        tglskrg();
        
        //Menampilkan nomor otomatis
        buatnomor();
        
        //Menampilkan judul tabel
        aturTabel();
        jkd_brg.requestFocus();
    }
    
    //Perintah tanggal otomatis
    public void tglskrg(){
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd MMMM yyyy");
        String tanggal = format.format(skrg);
        jtgl_skrg.setText(format.format(skrg));
    }

    //Perintah menampilkan nomor otomatis
    public void buatnomor(){
        try {
            ResultSet rs = db.ambilData("Select no_trans as auto from ttrans_jual ORDER by no_trans desc");
            
            if (rs.next()) {
                int no_u = Integer.parseInt(rs.getString("auto")) + 1;
                jno_trans.setText(Integer.toString(no_u));
            } else {
                int no_t = 1;
                jno_trans.setText(Integer.toString(no_t));
            }
            rs.close();
        } catch (Exception e) {
        }
    }
    
    //Perintah menampilkan judul tabel pada form transaksi jual
    public void aturTabel(){
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jml Barang");
        jtabel.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jno_trans = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jkd_brg = new javax.swing.JTextField();
        jnama_brg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtgl_skrg = new javax.swing.JTextField();
        jstok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jjml_harga = new javax.swing.JTextField();
        ttambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jbayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jkembali = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbtsimpan = new javax.swing.JButton();
        jbtbatal = new javax.swing.JButton();
        jbtKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jjml = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel1.setText("No Transaksi");

        jno_trans.setEditable(false);
        jno_trans.setBackground(new java.awt.Color(0, 0, 0));
        jno_trans.setForeground(new java.awt.Color(255, 255, 255));
        jno_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jno_transActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel2.setText("KODE BARANG NAMA BARANG");

        jkd_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkd_brgActionPerformed(evt);
            }
        });

        jnama_brg.setEditable(false);
        jnama_brg.setBackground(new java.awt.Color(0, 0, 0));
        jnama_brg.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel3.setText("Tanggal");

        jtgl_skrg.setEditable(false);
        jtgl_skrg.setBackground(new java.awt.Color(0, 0, 0));
        jtgl_skrg.setForeground(new java.awt.Color(255, 255, 255));
        jtgl_skrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtgl_skrgActionPerformed(evt);
            }
        });

        jstok.setEditable(false);
        jstok.setBackground(new java.awt.Color(0, 0, 0));
        jstok.setForeground(new java.awt.Color(255, 255, 255));
        jstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstokActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel5.setText("STOK");

        jharga.setEditable(false);
        jharga.setBackground(new java.awt.Color(0, 0, 0));
        jharga.setForeground(new java.awt.Color(255, 255, 255));
        jharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhargaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel6.setText("HARGA");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel7.setText("Pilih item barang dibawah ini apabila hendak membatalkan transaksi pembelian barang");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel8.setText("JML HARGA");

        jjml_harga.setEditable(false);
        jjml_harga.setBackground(new java.awt.Color(0, 0, 0));
        jjml_harga.setForeground(new java.awt.Color(255, 255, 255));
        jjml_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjml_hargaActionPerformed(evt);
            }
        });

        ttambah.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        ttambah.setText("TAMBAH");
        ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttambahActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel9.setText("TOTAL");

        jtotal.setEditable(false);

        jbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbayarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel10.setText("BAYAR");

        jkembali.setEditable(false);
        jkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkembaliActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel11.setText("KEMBALI");

        jbtsimpan.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jbtsimpan.setText("Simpan");
        jbtsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsimpanActionPerformed(evt);
            }
        });

        jbtbatal.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jbtbatal.setText("Batal");
        jbtbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbatalActionPerformed(evt);
            }
        });

        jbtKeluar.setBackground(new java.awt.Color(255, 102, 102));
        jbtKeluar.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jbtKeluar.setText("Keluar");
        jbtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtKeluarActionPerformed(evt);
            }
        });

        jtabel.setBackground(new java.awt.Color(0, 0, 0));
        jtabel.setForeground(new java.awt.Color(255, 255, 255));
        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                ""
            }
        ));
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabel);

        jjml.setBackground(new java.awt.Color(0, 0, 0));
        jjml.setForeground(new java.awt.Color(255, 255, 255));
        jjml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjmlActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jLabel12.setText("JUMLAH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel9)
                                        .addGap(144, 144, 144)
                                        .addComponent(jLabel10)
                                        .addGap(145, 145, 145)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtbatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtKeluar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ttambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jjml_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jstok, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jharga, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jjml, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jno_trans, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtgl_skrg, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(42, 42, 42))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jno_trans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtgl_skrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkd_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jnama_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jjml_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttambah))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jkembali, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbayar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtbatal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtsimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jno_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jno_transActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_jno_transActionPerformed

    private void jbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbayarActionPerformed
        // TODO add your handling code here:
        int a1, a2, kemb;
        a1 = Integer.parseInt(jtotal.getText());
        a2 = Integer.parseInt(jbayar.getText());
        kemb = a2 - a1;
        jkembali.setText(String.valueOf(kemb));
        jbtsimpan.requestFocus();
    }//GEN-LAST:event_jbayarActionPerformed

    private void jbtsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsimpanActionPerformed
        // TODO add your handling code here:
        sumTotal = 0;
        int row = jtabel.getRowCount();
        
        try {
//            ResultSet rs = db.ambilData("select * from ttrans_jual where no_trans ='"+jno_trans.getText()+"'");
//            
//            if (rs.next()) {
//                JOptionPane.showMessageDialog(null, "No Transaksi sudah berakhir");
//            } else {
                
            for(int i = 0; i < row; i++){
                db.aksi("INSERT INTO tdetail_jual(no_trans,tanggal,kd_brg,jml,harga)values"
                +"('" + jno_trans.getText() + "','" + jtgl_skrg.getText() + "'"
                    + ",'" + jtabel.getValueAt(i, 0) + "','" + jtabel.getValueAt(i, 3) + "'"
                + ",'"+jtabel.getValueAt(i, 2) + "')");
                
                db.aksi("update tbarang set jml=jml-" + jtabel.getValueAt(i, 3) + " where kd_brg='" + jtabel.getValueAt(i, 0) + "'");
            }
            db.aksi("insert into ttrans_jual(no_trans,tanggal,total)values('"+jno_trans.getText() + "',"
                + "'" + jtgl_skrg.getText() + "','" +jtotal.getText() + "')");
            JOptionPane.showMessageDialog(null, "Data telah tersimpan");
            
//            }
            
            model.setRowCount(0);
            jtotal.setText("");
            buatnomor();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtsimpanActionPerformed

    private void jtgl_skrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtgl_skrgActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jtgl_skrgActionPerformed

    private void jkd_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkd_brgActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = db.ambilData("select * from tbarang where kd_brg='" + jkd_brg.getText() + "'");
            if (rs.next()) {
                jnama_brg.setText(rs.getString("nama_brg"));
                jharga.setText(rs.getString("harga"));
                jstok.setText(rs.getString("jml"));
                jjml.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Kode Belum Terdaftar");
                jkd_brg.selectAll();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jkd_brgActionPerformed

    private void jstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstokActionPerformed

    private void jhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhargaActionPerformed

    private void jbtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtKeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Yakin keluar dari aplikasi ini?",
                "Reminder RPL", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            this.dispose(); 
        }
    }//GEN-LAST:event_jbtKeluarActionPerformed

    private void jjmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjmlActionPerformed
        // TODO add your handling code here:
        int a1, a2, tot, stok_brg = Integer.parseInt(jstok.getText());
        if (stok_brg > 1) {
            a1 = Integer.parseInt(jharga.getText());
            a2 = Integer.parseInt(jjml.getText());
            tot = a1 * a2;
            jjml_harga.setText(String.valueOf(tot));
            ttambah.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Maaf, \nstok sudah mencapai stok minimal");
        }
    }//GEN-LAST:event_jjmlActionPerformed

    private void ttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttambahActionPerformed
        // TODO add your handling code here
        try {
            int n = JOptionPane.showConfirmDialog(this, "Tambah item lagi?", "RPL Message", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null);
            if (n == JOptionPane.YES_OPTION) {
                long qty, hrg;
                model.addRow(new Object[]{jkd_brg.getText(), jnama_brg.getText(), jharga.getText(), jjml.getText()});
                jtabel.setModel(model);
                qty = Long.parseLong(jjml.getText());
                hrg = Long.parseLong(jharga.getText());
                sumTotal += (hrg * qty);
                jtotal.setText(String.valueOf(sumTotal));
                jkd_brg.requestFocus();
                jkd_brg.setText("");
                jnama_brg.setText("");
                jharga.setText("");
                jstok.setText("");  
                jjml.setText("");
                jjml_harga.setText("");
            }else if (n == JOptionPane.NO_OPTION) {
                long qty, hrg;
                model.addRow(new Object[]{jkd_brg.getText(), jnama_brg.getText(), jharga.getText(), jjml.getText()});
                jtabel.setModel(model);
                qty = Long.parseLong(jjml.getText());
                hrg = Long.parseLong(jharga.getText());
                sumTotal += (hrg * qty);
                jtotal.setText(String.valueOf(sumTotal));
                jkd_brg.setText("");
                jnama_brg.setText("");
                jharga.setText("");
                jstok.setText("");
                jjml.setText("");
                jjml_harga.setText("");
                jbayar.requestFocus();
            } else {
                jbayar.requestFocus();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ttambahActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked
        // TODO add your handling code here:
        try {
            int n = JOptionPane.showConfirmDialog(this, "Anda yakin membatalkan item ini?", "RPL Message",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null);
            if (n == JOptionPane.YES_OPTION){
                model.removeRow(jtabel.getSelectedRow());
                int row = jtabel.getRowCount();
                int tot = 0, hrg, jml;
                for (int i = 0; i < row; i++){
                    hrg = Integer.parseInt(jtabel.getValueAt(i, 2).toString());
                    jml = Integer.parseInt(jtabel.getValueAt(i, 3).toString());
                    tot += (hrg * jml);
                }
                jtotal.setText(String.valueOf(tot));
            }else if(n == JOptionPane.NO_OPTION){
                return;
            }else{
                return;
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtabelMouseClicked

    private void jbtbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtbatalActionPerformed

    private void jkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkembaliActionPerformed

    private void jjml_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjml_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjml_hargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jbayar;
    private javax.swing.JButton jbtKeluar;
    private javax.swing.JButton jbtbatal;
    private javax.swing.JButton jbtsimpan;
    private javax.swing.JTextField jharga;
    private javax.swing.JTextField jjml;
    private javax.swing.JTextField jjml_harga;
    private javax.swing.JTextField jkd_brg;
    private javax.swing.JTextField jkembali;
    private javax.swing.JTextField jnama_brg;
    private javax.swing.JTextField jno_trans;
    private javax.swing.JTextField jstok;
    private javax.swing.JTable jtabel;
    private javax.swing.JTextField jtgl_skrg;
    private javax.swing.JTextField jtotal;
    private javax.swing.JButton ttambah;
    // End of variables declaration//GEN-END:variables

    
}
